github: [mehran98ha]
patreon: mehran98ha
open_collective: mehran98ha
ko_fi: mehran98ha
tidelift: npm/mehran98ha
liberapay: mehran98ha
issuehunt: mehran98ha
otechie: mehran98ha
custom: ['https://mehran98ha.github.io', 'https://paypal.me/mehran98ha','https://donorbox.org/mehran98ha']
